# Generated by Django 6.0.3 on 2026-04-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='faltas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alunos',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alunos',
            name='numero',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
