# Generated by Django 6.0.3 on 2026-04-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alunos_faltas_alunos_nome_alunos_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='faltas',
            field=models.IntegerField(verbose_name='default=0'),
        ),
    ]
