# Generated by Django 6.0.3 on 2026-04-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_alunos_faltas'),
    ]

    operations = [
        migrations.CreateModel(
            name='aulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.CharField(max_length=100)),
            ],
        ),
    ]
