# Generated by Django 6.0.3 on 2026-04-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aulas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas',
            name='aula',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
