# Generated by Django 6.0.3 on 2026-04-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_aulas_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='contatos',
            field=models.CharField(default='Sem contato', max_length=200),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='faltas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aulas',
            name='aula',
            field=models.CharField(default='0', max_length=100, unique=True),
        ),
    ]
