# Generated by Django 6.0.3 on 2026-04-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alunos_contatos_alter_alunos_faltas_alter_aulas_aula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(unique=True)),
                ('absences', models.IntegerField(default=0)),
                ('contacts', models.CharField(default='No contact', max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='aulas',
            new_name='Classes',
        ),
        migrations.DeleteModel(
            name='Alunos',
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='aula',
            new_name='class_number',
        ),
    ]
